@extends('layouts.admin')

@section('title', 'Create New Report')
@section('page-title', 'Create New Report')

@section('content')
<!-- Futuristic Header Section -->
<div class="mb-4 mb-md-5 futuristic-card p-4 p-md-5" style="border-color: rgba(124, 58, 237, 0.3); background: linear-gradient(135deg, rgba(124, 58, 237, 0.1), rgba(0, 102, 255, 0.1));">
    <div class="d-flex align-items-center gap-3">
        <a href="{{ route('admin.reports.index') }}" class="btn btn-neon btn-sm rounded-circle d-flex align-items-center justify-content-center" style="width: 45px; height: 45px;">
            <i class="fas fa-arrow-left"></i>
        </a>
        <div>
            <h1 class="h3 h4-md fw-bold mb-1" style="color: #7c3aed;">Create New Report</h1>
            <p class="mb-0 small" style="color: var(--text-secondary);">Enter the report details</p>
        </div>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-12 col-lg-10">
        <form method="POST" action="{{ route('admin.reports.store') }}">
        @csrf
            
            <!-- Report Information Card -->
            <div class="futuristic-card p-4 p-md-5 mb-4" style="border-color: rgba(0, 102, 255, 0.2);">
                <div class="row">
                    <div class="col-12 col-md-3 mb-4 mb-md-0">
                        <h3 class="h5 fw-bold mb-2" style="color: var(--text-primary);">Report Information</h3>
                        <p class="small mb-0" style="color: var(--text-secondary);">Enter the report details.</p>
                </div>
                    <div class="col-12 col-md-9">
                        <div class="row g-3">
                            <div class="col-12">
                                <label for="report_type" class="form-label fw-semibold" style="color: var(--text-primary);">Report Type</label>
                            <input type="text" name="report_type" id="report_type" required
                                       class="form-control @error('report_type') is-invalid @enderror"
                                   value="{{ old('report_type') }}" placeholder="e.g., Monthly Revenue, Tenant Report, Maintenance Summary">
                            @error('report_type')
                                    <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>

                            <div class="col-12 col-md-6">
                                <label for="generated_by_id" class="form-label fw-semibold" style="color: var(--text-primary);">Generated By</label>
                                <select name="generated_by_id" id="generated_by_id" required class="form-select @error('generated_by_id') is-invalid @enderror">
                                <option value="">Select user</option>
                            </select>
                            @error('generated_by_id')
                                    <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>

                            <div class="col-12 col-md-6">
                                <label for="generated_date" class="form-label fw-semibold" style="color: var(--text-primary);">Generated Date</label>
                            <input type="date" name="generated_date" id="generated_date" required
                                       class="form-control @error('generated_date') is-invalid @enderror"
                                   value="{{ old('generated_date', date('Y-m-d')) }}">
                            @error('generated_date')
                                    <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>

                            <div class="col-12">
                                <label for="content" class="form-label fw-semibold" style="color: var(--text-primary);">Report Content</label>
                            <textarea name="content" id="content" rows="8" required
                                          class="form-control @error('content') is-invalid @enderror"
                                      placeholder="Enter the report content here...">{{ old('content') }}</textarea>
                            @error('content')
                                    <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>

            <!-- Form Actions -->
            <div class="d-flex justify-content-end gap-3">
                <a href="{{ route('admin.reports.index') }}" class="btn btn-secondary">
                Cancel
            </a>
                <button type="submit" class="btn btn-neon">
                    <i class="fas fa-plus me-2"></i>Create Report
            </button>
        </div>
    </form>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const userSelect = document.getElementById('generated_by_id');
    
    const admins = @json($admins);
    const staff = @json($staff);
    const tenants = @json($tenants);
    
    // Populate all users in the dropdown with role indicators
    userSelect.innerHTML = '<option value="">Select user</option>';
    
    // Add Admin option
    const adminOption = document.createElement('option');
    adminOption.value = 'admin';
    adminOption.textContent = 'Admin';
    adminOption.dataset.userType = 'admin';
    @if(old('generated_by_id') == 'admin')
        adminOption.selected = true;
    @endif
    userSelect.appendChild(adminOption);
    
    // Add Tenant option
    const tenantOption = document.createElement('option');
    tenantOption.value = 'tenant';
    tenantOption.textContent = 'Tenant';
    tenantOption.dataset.userType = 'tenant';
    @if(old('generated_by_id') == 'tenant')
        tenantOption.selected = true;
    @endif
    userSelect.appendChild(tenantOption);
    
    // Add Staff option
    const staffOption = document.createElement('option');
    staffOption.value = 'staff';
    staffOption.textContent = 'Staff';
    staffOption.dataset.userType = 'staff';
    @if(old('generated_by_id') == 'staff')
        staffOption.selected = true;
    @endif
    userSelect.appendChild(staffOption);
});
</script>
@endsection
