@extends('layouts.admin')

@section('title', 'Report Details')
@section('page-title', 'Report Details')

@section('content')
<!-- Futuristic Header Section -->
<div class="mb-4 mb-md-5 futuristic-card p-4 p-md-5" style="border-color: rgba(124, 58, 237, 0.3); background: linear-gradient(135deg, rgba(124, 58, 237, 0.1), rgba(0, 102, 255, 0.1));">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3">
        <div class="d-flex align-items-center gap-3">
            <a href="{{ route('admin.reports.index') }}" class="btn btn-neon btn-sm rounded-circle d-flex align-items-center justify-content-center" style="width: 45px; height: 45px;">
                <i class="fas fa-arrow-left"></i>
            </a>
            <div>
                <h1 class="h3 h4-md fw-bold mb-1" style="color: #7c3aed;">Report #{{ $report->report_id }}</h1>
                <p class="mb-0 small" style="color: var(--text-secondary);">Complete report details and information</p>
            </div>
        </div>
        <div class="d-flex gap-2">
                @if($report->file_path)
                <a href="{{ route('admin.reports.download', $report) }}" class="btn" style="background: linear-gradient(135deg, #22c55e, #16a34a); color: white; border: none;">
                    <i class="fas fa-download me-2"></i>Download
                    </a>
                @endif
            <a href="{{ route('admin.reports.edit', $report) }}" class="btn" style="background: linear-gradient(135deg, #f59e0b, #fbbf24); color: white; border: none;">
                <i class="fas fa-edit me-2"></i>Edit
                </a>
            </div>
        </div>
</div>

<div class="row g-4">
    <!-- Report Information Card -->
    <div class="col-12">
        <div class="futuristic-card" style="border-color: rgba(0, 102, 255, 0.2);">
            <div class="p-4 border-bottom" style="border-color: rgba(0, 102, 255, 0.2) !important;">
                <h3 class="h5 fw-bold mb-1" style="color: var(--text-primary);">Report Information</h3>
                <p class="small mb-0" style="color: var(--text-secondary);">Complete report details</p>
            </div>
            <div class="p-4">
                <div class="row g-3">
                    <div class="col-12 col-md-4">
                        <dt class="small fw-semibold mb-2" style="color: var(--text-secondary);">Report ID</dt>
                        <dd class="fw-bold" style="color: var(--text-primary);">#{{ $report->report_id }}</dd>
                </div>
                    <div class="col-12 col-md-4">
                        <dt class="small fw-semibold mb-2" style="color: var(--text-secondary);">Report Type</dt>
                        <dd style="color: var(--text-primary);">{{ $report->report_type }}</dd>
                </div>
                    <div class="col-12 col-md-4">
                        <dt class="small fw-semibold mb-2" style="color: var(--text-secondary);">Generated By</dt>
                        <dd style="color: var(--text-primary);">
                        {{ $report->generatedBy->name ?? 'N/A' }} 
                            <span style="color: var(--text-secondary);">({{ class_basename($report->generated_by_type) }})</span>
                    </dd>
                </div>
                    <div class="col-12 col-md-6">
                        <dt class="small fw-semibold mb-2" style="color: var(--text-secondary);">Generated Date</dt>
                        <dd style="color: var(--text-primary);">{{ $report->generated_date ? $report->generated_date->format('F j, Y') : 'N/A' }}</dd>
                    </div>
                    <div class="col-12 col-md-6">
                        <dt class="small fw-semibold mb-2" style="color: var(--text-secondary);">Created</dt>
                        <dd style="color: var(--text-primary);">{{ $report->created_at->format('F j, Y \a\t g:i A') }}</dd>
                    </div>
                </div>
                </div>
        </div>
    </div>

    <!-- Report Content -->
    <div class="col-12">
        <div class="futuristic-card" style="border-color: rgba(0, 102, 255, 0.2);">
            <div class="p-4 border-bottom" style="border-color: rgba(0, 102, 255, 0.2) !important;">
                <h3 class="h5 fw-bold mb-1" style="color: var(--text-primary);">Report Content</h3>
                <p class="small mb-0" style="color: var(--text-secondary);">The detailed content of this report</p>
        </div>
            <div class="p-4">
                <div style="color: var(--text-primary); white-space: pre-wrap;">{!! nl2br(e($report->content)) !!}</div>
            </div>
        </div>
    </div>
</div>
@endsection
