<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Report;
use App\Models\Admin;
use App\Models\Staff;
use App\Models\Tenant;
use Illuminate\Support\Facades\Storage;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        // Get all reports with their generated by relationship
        $reports = Report::with('generatedBy')->latest('generated_date')->get();
        
        // Check if user wants to view revenue data
        $view = $request->get('view');
        
        if ($view === 'revenue') {
            // Get monthly revenue data for the last 12 months
            $monthlyEarnings = [];
            for ($i = 11; $i >= 0; $i--) {
                $month = now()->subMonths($i);
                $monthKey = $month->format('Y-m');
                $monthName = $month->format('F Y');
                
                $revenue = \App\Models\Payment::where('status', 'completed')
                    ->whereRaw('DATE_FORMAT(payment_date, "%Y-%m") = ?', [$monthKey])
                    ->sum('amount');
                
                $monthlyEarnings[] = [
                    'month' => $monthName,
                    'month_key' => $monthKey,
                    'revenue' => $revenue,
                    'formatted_revenue' => number_format($revenue, 2)
                ];
            }
            
            // Get current month revenue for comparison
            $currentMonthRevenue = \App\Models\Payment::where('status', 'completed')
                ->whereRaw('DATE_FORMAT(payment_date, "%Y-%m") = ?', [now()->format('Y-m')])
                ->sum('amount');
            
            // Get previous month revenue for growth calculation
            $previousMonthRevenue = \App\Models\Payment::where('status', 'completed')
                ->whereRaw('DATE_FORMAT(payment_date, "%Y-%m") = ?', [now()->subMonth()->format('Y-m')])
                ->sum('amount');
            
            $growthRate = $previousMonthRevenue > 0 ? 
                round((($currentMonthRevenue - $previousMonthRevenue) / $previousMonthRevenue) * 100, 1) : 0;
            
            return view('admin.reports.index', compact('reports', 'monthlyEarnings', 'currentMonthRevenue', 'growthRate'));
        }
        
        return view('admin.reports.index', compact('reports'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $admins = Admin::all();
        $staff = Staff::all();
        $tenants = Tenant::all();
        
        return view('admin.reports.create', compact('admins', 'staff', 'tenants'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'report_type' => 'required|string|max:255',
            'generated_by_id' => 'required|in:admin,staff,tenant',
            'generated_date' => 'required|date',
            'content' => 'required|string',
        ]);

        $data = $request->all();
        
        // Set the generated_by_type based on the selected role
        switch($request->generated_by_id) {
            case 'admin':
                $data['generated_by_type'] = 'App\Models\Admin';
                $data['generated_by_id'] = 1; // Default admin ID
                break;
            case 'staff':
                $data['generated_by_type'] = 'App\Models\Staff';
                $data['generated_by_id'] = 1; // Default staff ID
                break;
            case 'tenant':
                $data['generated_by_type'] = 'App\Models\Tenant';
                $data['generated_by_id'] = 1; // Default tenant ID
                break;
            default:
                $data['generated_by_type'] = 'App\Models\Admin';
                $data['generated_by_id'] = 1;
                break;
        }
        
        Report::create($data);

        return redirect()->route('admin.reports.index')
            ->with('success', 'Report created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Report $report)
    {
        $report->load('generatedBy');
        
        return view('admin.reports.show', compact('report'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        $admins = Admin::all();
        $staff = Staff::all();
        $tenants = Tenant::all();
        
        return view('admin.reports.edit', compact('report', 'admins', 'staff', 'tenants'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Report $report)
    {
        $request->validate([
            'report_type' => 'required|string|max:255',
            'generated_by_id' => 'required|in:admin,staff,tenant',
            'generated_date' => 'required|date',
            'content' => 'required|string',
        ]);

        $data = $request->all();
        
        // Set the generated_by_type based on the selected role
        switch($request->generated_by_id) {
            case 'admin':
                $data['generated_by_type'] = 'App\Models\Admin';
                $data['generated_by_id'] = 1; // Default admin ID
                break;
            case 'staff':
                $data['generated_by_type'] = 'App\Models\Staff';
                $data['generated_by_id'] = 1; // Default staff ID
                break;
            case 'tenant':
                $data['generated_by_type'] = 'App\Models\Tenant';
                $data['generated_by_id'] = 1; // Default tenant ID
                break;
            default:
                $data['generated_by_type'] = 'App\Models\Admin';
                $data['generated_by_id'] = 1;
                break;
        }
        
        $report->update($data);

        return redirect()->route('admin.reports.index')
            ->with('success', 'Report updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        // Delete associated file if it exists
        if ($report->file_path && Storage::exists($report->file_path)) {
            Storage::delete($report->file_path);
        }

        $report->delete();

        return redirect()->route('admin.reports.index')
            ->with('success', 'Report deleted successfully.');
    }

    /**
     * Download the report file.
     */
    public function download(Report $report)
    {
        if (!$report->file_path || !Storage::exists($report->file_path)) {
            return redirect()->back()->with('error', 'File not found.');
        }

        return Storage::download($report->file_path);
    }
}
